### ISSUE TITLE
Need a way to unescape regexp

### ISSUE THREAD

**Issue by colt005** [Chinmay-KB/stringr#4]
Currently there is a function to escape a regex string 

`'500-200'.escapeRegExp() ` returns --> **r"500\\-200"**

Similarly, add a new function `unEscapeRegExp()` that will un-escape the regex and return it as a regular string. 

`'r"500\\-200"'.unEscapeRegExp()`   should return --> **'500-200'**

**Comment by Chinmay-KB** [comment]
Thank you for opening a feature request @colt005 . This surely will be a good addition to the already OP package. Would you like to work on it or shall I do it myself.

**Comment by colt005** [comment]
Yes I would like to give you an helping hand. You can assign the issue to me.

**Comment by Chinmay-KB** [comment]
All the very best with this feature mr colt005 🚀

**Comment by Chinmay-KB** [comment]
L
